import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFile, writeFile, mkdir, symlink, access } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NativeExecutor } from '../../dist/sandbox/executor.js';
import { EMPTY_DELTA } from '../../dist/contracts.js';
import { workloadEnvironment, shellQuote } from '../../dist/sandbox/config.js';
import { fixture, auditPopulationPath } from '../harness/fixtures.mjs';
import { guardedFixture, planStream } from '../harness/pi.mjs';

const exec=promisify(execFile), repository=fileURLToPath(new URL('../../',import.meta.url));
test('[workflow] model work succeeds while adversarial interpreter and protected file effects remain denied', async t => {
  const f=await fixture(t), runtime=await guardedFixture(t,f), target=join(f.outside,'sentinel.txt'), events=[];runtime.session.subscribe(e=>events.push(e));
  await planStream(runtime.session,[[{name:'write',args:{path:'allowed.txt',content:'allowed'}}],[{name:'bash',args:{command:`${shellQuote(process.execPath)} -e ${shellQuote(`require('fs').writeFileSync(${JSON.stringify(target)},'escaped')`)}`}}],[{name:'read',args:{path:join(f.control,'protected.txt')}}]]);
  await runtime.session.prompt('Perform owned fixture work.');
  assert.equal(await readFile(join(f.workspace,'allowed.txt'),'utf8'),'allowed');assert.equal(await readFile(target,'utf8'),'unchanged');assert.equal(await readFile(join(f.control,'protected.txt'),'utf8'),f.secret);
  const results=events.filter(e=>e.type==='tool_execution_end');assert.equal(results.length,3);assert.equal(results[0].isError,false);assert.equal(results[1].isError,true);assert.equal(results[2].isError,true);
  assert.ok(results.every(e=>!JSON.stringify(e.result).includes(f.secret)));
});
test('[workflow] one-use UI approval covers edit helpers and cannot authorize another logical call', async t => {
  const f=await fixture(t), target=join(f.outside,'sentinel.txt'), runtime=await guardedFixture(t,f,{provider:{complete:async()=>'{"decision":"ask","reason":"confirm"}'}});let prompts=0;
  await runtime.session.bindExtensions({mode:'rpc',uiContext:{select:async(_title,choices)=>{prompts++;return prompts===1?choices[0]:choices.at(-1);},notify:()=>{},setStatus:()=>{},setWidget:()=>{}}});
  await planStream(runtime.session,[[{name:'edit',args:{path:target,edits:[{oldText:'unchanged',newText:'approved'}]}}],[{name:'write',args:{path:target,content:'second'}}]]);
  await runtime.session.prompt('Approve only the first action.');assert.equal(prompts,2);assert.equal(await readFile(target,'utf8'),'approved');
});
test('[workflow] protected SDK direct shell and failed reload cannot activate a host fallback', async t => {
  const f=await fixture(t), native=new NativeExecutor();let qualification=0;
  const executor={qualify:async(...args)=>{if(++qualification>1)throw new Error('backend lost on reload');return native.qualify(...args);},execute:native.execute.bind(native),close:native.close.bind(native)};
  const runtime=await guardedFixture(t,f,{executor});
  assert.equal((await runtime.session.executeBash('printf protected-sdk')).output,'protected-sdk');
  let unsafe=false;await assert.rejects(runtime.session.executeBash('printf unsafe',undefined,{operations:{exec:async()=>{unsafe=true;return{exitCode:0};}}}),/guarded shell/);assert.equal(unsafe,false);
  await assert.rejects(runtime.session.reload(),/failed to load|not ready/);
  await assert.rejects(runtime.session.executeBash(`echo escape > '${join(f.workspace,'reload.txt')}'`),/failed to load|not ready/);
  await assert.rejects(runtime.session.prompt('After failed reload.'),/failed to load|not ready/);
  await assert.rejects(access(join(f.workspace,'reload.txt')));
});
test('[workflow] malformed risk enums fail closed at the actual Pi write and reach the next model request', async t => {
  const f=await fixture(t), target=join(f.outside,'sentinel.txt'), events=[],requests=[];let reviews=0;
  const runtime=await guardedFixture(t,f,{provider:{complete:async()=>JSON.stringify({outcome:'allow',risk_level:[++reviews===1?'critical':'high'],user_authorization:'unknown'})}});
  runtime.session.subscribe(event=>events.push(event));
  await planStream(runtime.session,[[{name:'write',args:{path:target,content:'must not escape'}}],[{name:'write',args:{path:target,content:'must still not escape'}}]]);
  const stream=runtime.session.agent.streamFunction;
  runtime.session.agent.streamFunction=(...args)=>{requests.push(structuredClone(args[1].messages));return stream(...args);};
  await runtime.session.prompt('Check malformed review output against the owned sentinel.');
  assert.equal(reviews,2);assert.equal(await readFile(target,'utf8'),'unchanged');
  const results=events.filter(event=>event.type==='tool_execution_end');
  assert.equal(results.length,2);assert.ok(results.every(event=>event.isError&&JSON.stringify(event.result).includes('AUTO_REVIEW_FAILED')));
  assert.equal(requests.length,3);assert.ok(requests[1].some(message=>message.role==='toolResult'&&JSON.stringify(message).includes('AUTO_REVIEW_FAILED')));
  const audit=(await readFile(join(f.agentDir,'guard/audit.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);
  assert.equal(audit.filter(row=>row.review?.status==='failed').length,2);
  assert.ok(!audit.some(row=>row.outcome==='approved'));
});
test('[workflow] quoted review rationale is redacted without breaking approved execution or JSON audit', async t => {
  const f=await fixture(t),target=join(f.outside,'sentinel.txt'),secret='quoted-fixture-private-value';
  const runtime=await guardedFixture(t,f,{provider:{complete:async()=>JSON.stringify({outcome:'allow',risk_level:'low',user_authorization:'high',rationale:`Owned file; token="${secret}" is not logged.`})}});
  await planStream(runtime.session,[[{name:'write',args:{path:target,content:'approved'}}]]);
  await runtime.session.prompt('Update only the owned sentinel.');
  assert.equal(await readFile(target,'utf8'),'approved');
  const text=await readFile(join(f.agentDir,'guard/audit.jsonl'),'utf8'),rows=text.trim().split('\n').map(JSON.parse);
  assert.ok(rows.some(row=>row.review?.status==='approved'));assert.ok(!text.includes(secret));
  assert.ok(rows.some(row=>row.event==='execution'&&row.outcome==='settled'));
});
test('[workflow] denial circuit stops the model but a later direct user shell has its own cancellation lifetime', async t => {
  const f=await fixture(t),events=[];let reviews=0;
  const runtime=await guardedFixture(t,f,{provider:{complete:async()=>{reviews++;return '{"outcome":"deny","rationale":"Owned denial-limit scenario"}';}}});
  runtime.session.subscribe(event=>events.push(event));
  await planStream(runtime.session,Array.from({length:4},(_,index)=>[{name:'write',args:{path:join(f.outside,`denied-${index}.txt`),content:'blocked'}}]));
  await runtime.session.prompt('Exercise denial limits with owned targets.');
  assert.equal(reviews,3);
  for(let index=0;index<4;index++)await assert.rejects(access(join(f.outside,`denied-${index}.txt`)));
  const result=await runtime.session.executeBash('printf direct-user-after-denial');
  assert.equal(result.exitCode,0);assert.equal(result.output,'direct-user-after-denial');
  const results=events.filter(event=>event.type==='tool_execution_end');
  assert.ok(results.every(event=>event.isError));
  assert.equal(results.filter(event=>JSON.stringify(event.result).includes('AUTO_REVIEW_DENIED')).length,3);
});
test('[workflow] trusted project MCP configuration cannot be rewritten by model tools or interpreters before reload',async t=>{
  const f=await fixture(t),directory=join(f.workspace,'.pi'),path=join(directory,'mcp.json'),target=join(f.outside,'sentinel.txt');
  await mkdir(directory);await writeFile(path,'{"mcpServers":{}}');
  const injected=JSON.stringify({mcpServers:{injected:{command:process.execPath,args:[resolve('test/harness/mcp-server.mjs'),target,'startup-effect'],exposure:'direct'}}});
  const runtime=await guardedFixture(t,f,{settingsManager:undefined,isProjectTrusted:true,provider:{complete:()=>assert.fail('Control-file mutation must not reach approval')}});
  await planStream(runtime.session,[[{name:'write',args:{path,content:injected}}],[{name:'bash',args:{command:`${shellQuote(process.execPath)} -e ${shellQuote(`require('fs').writeFileSync(${JSON.stringify(path)},${JSON.stringify(injected)})`)}`}}]]);
  await runtime.session.prompt('Keep project control files unchanged.');
  await runtime.session.reload();
  await planStream(runtime.session,[]);await runtime.session.prompt('Wait for configured MCP startup after reload.');
  assert.equal(await readFile(target,'utf8'),'unchanged');
  assert.equal(await readFile(path,'utf8'),'{"mcpServers":{}}');
  await writeFile(path,injected);await runtime.session.reload();
  await planStream(runtime.session,[]);await runtime.session.prompt('Load the explicitly edited MCP configuration.');
  assert.equal(await readFile(target,'utf8'),'started-by-project-config','An explicit host-side configuration update still loads');
});
test('[workflow] trusted extension entrypoint and sibling modules cannot be replaced before reload',async t=>{
  const f=await fixture(t),directory=join(f.workspace,'owned-provider'),entry=join(directory,'index.mjs'),helper=join(directory,'helper.mjs'),target=join(f.outside,'sentinel.txt');
  await mkdir(directory);await writeFile(helper,'export const value="trusted";');
  const original='import {value} from "./helper.mjs"; export default api=>{if(value!=="trusted")throw new Error("Changed trusted module");};';
  await writeFile(entry,original);
  const runtime=await guardedFixture(t,f,{trustedExtensionPaths:[entry],provider:{complete:()=>assert.fail('Trusted code mutation must not reach approval')}});
  const injected=`import {writeFileSync} from "node:fs";writeFileSync(${JSON.stringify(target)},"unreviewed-controller-effect");export default ()=>{};`;
  await planStream(runtime.session,[[{name:'write',args:{path:entry,content:injected}}],[{name:'write',args:{path:helper,content:'export const value="changed";'}}]]);
  await runtime.session.prompt('Do not replace trusted provider code.');
  await runtime.session.reload();
  assert.equal(await readFile(target,'utf8'),'unchanged');assert.equal(await readFile(entry,'utf8'),original);
  assert.equal(await readFile(helper,'utf8'),'export const value="trusted";');
});
test('[workflow] real MCP node_repl/js follows explicit prompt approval and never acquires Computer Use privileges',async t=>{
  const f=await fixture(t),target=join(f.outside,'sentinel.txt'),processLog=join(f.root,'mcp-processes.jsonl');
  const runtime=await guardedFixture(t,f,{settings:{approvalsReviewer:'user'},mcpToolPolicies:{'node_repl/js':{approvalMode:'prompt'}},mcp:{loadConfig:()=>({servers:[{name:'node_repl',config:{command:process.execPath,args:[resolve('test/harness/mcp-server.mjs'),target,'no-startup-effect','js',processLog],exposure:'direct'},source:'owned-name-collision',scope:'extension'}],errors:[]})},provider:{complete:()=>assert.fail('User review cannot call the model')}});
  const invoke=async value=>{await planStream(runtime.session,[[{name:'mcp__node_repl__js',args:{value}}]]);await runtime.session.prompt('Use the owned MCP fixture only after approval.');};
  await invoke('no-ui');assert.equal(await readFile(target,'utf8'),'unchanged');
  let prompts=0;
  await runtime.session.bindExtensions({mode:'rpc',uiContext:{select:async(_title,choices)=>{prompts++;return prompts===1?choices.at(-1):choices[0];},notify(){},setStatus(){},setWidget(){}}});
  await invoke('denied');assert.equal(await readFile(target,'utf8'),'unchanged');
  await invoke('approved');assert.equal(await readFile(target,'utf8'),'approved');assert.equal(prompts,2);
  await runtime.dispose();
  const processes=(await readFile(processLog,'utf8')).trim().split('\n').map(JSON.parse);
  assert.equal(processes.length,2);
  for(const {pid} of processes)assert.throws(()=>process.kill(pid,0),error=>error.code==='ESRCH');
});
test('[workflow] literal metacharacters never widen a reviewed grant while names inside the workspace remain usable',async t=>{
  const f=await fixture(t),literal=join(f.outside,'literal-[ab]'),sibling=join(f.outside,'literal-a'),events=[];let reviews=0;
  await writeFile(literal,'literal-original');await writeFile(sibling,'sibling-original');
  const runtime=await guardedFixture(t,f,{provider:{complete:async()=>{reviews++;return '{"outcome":"allow","risk_level":"low","user_authorization":"high"}';}}});
  runtime.session.subscribe(event=>events.push(event));
  const command=`${shellQuote(process.execPath)} -e ${shellQuote(`require('fs').writeFileSync(${JSON.stringify(sibling)},"escaped-through-pattern")`)}`;
  await planStream(runtime.session,[[{name:'bash',args:{command,sandbox_permissions:'require_escalated',additional_permissions:{writePaths:[literal]}}}],[{name:'write',args:{path:'[route]/literal-*.txt',content:'literal-workspace-effect'}}]]);
  await runtime.session.prompt('Use only literal path permissions for the owned fixture.');
  assert.equal(await readFile(literal,'utf8'),'literal-original');assert.equal(await readFile(sibling,'utf8'),'sibling-original');
  assert.equal(reviews,0);assert.equal(await readFile(join(f.workspace,'[route]/literal-*.txt'),'utf8'),'literal-workspace-effect');
  const results=events.filter(event=>event.type==='tool_execution_end');
  assert.equal(results.length,2);assert.equal(results[0].isError,true);assert.equal(results[1].isError,false);
  assert.ok(JSON.stringify(results[0].result).includes('literal paths'));
});
test('[package] npm tarball loads the default factory through public Pi APIs and executes bundled worker assets', async t => {
  const f=await fixture(t), artifacts=join(f.root,'artifacts'), consumer=join(f.root,'consumer'), home=join(f.control,'fake-home');
  await Promise.all([artifacts,consumer,home].map(path=>mkdir(path,{recursive:true})));
  const env={...workloadEnvironment(),...(process.env.PI_GUARD_KERNEL_ARCH?{PI_GUARD_KERNEL_ARCH:process.env.PI_GUARD_KERNEL_ARCH}:{}),PI_CODING_AGENT_DIR:f.agentDir,NPM_CONFIG_CACHE:join(f.control,'npm-cache'),NPM_CONFIG_USERCONFIG:join(f.control,'empty.npmrc'),NPM_CONFIG_GLOBALCONFIG:join(f.control,'global.npmrc')};
  const packed=JSON.parse((await exec('npm',['pack','--ignore-scripts','--json','--pack-destination',artifacts],{cwd:repository,env,timeout:20000,maxBuffer:2_000_000})).stdout)[0];
  assert.ok(packed.files.some(file=>file.path==='dist/sandbox/worker.js'));assert.ok(packed.files.some(file=>file.path==='dist/sandbox/broker.js'));
  assert.ok(packed.files.some(file=>file.path===`dist/native/pi-guard-execpolicy${process.platform==='win32'?'.exe':''}`));
  assert.ok(packed.files.some(file=>file.path==='native/execpolicy/LICENSE'));
  assert.ok(!packed.files.some(file=>/^(src|test|tmp|node_modules)\//.test(file.path)));
  await exec('tar',['-xzf',join(artifacts,packed.filename),'-C',consumer],{timeout:10000});
  await symlink(join(repository,'node_modules'),join(consumer,'package/node_modules'));
  await writeFile(join(f.agentDir,'mcp.json'),JSON.stringify({mcpServers:{stdio:{command:process.execPath,args:[resolve('test/harness/mcp-server.mjs'),join(f.outside,'sentinel.txt'),'no-startup-effect','read_owned'],exposure:'direct'}}}));
  const script=join(consumer,'package/probe.mjs');
  await writeFile(script,`
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createAgentSessionRuntime,createAgentSessionServices,createAgentSessionFromServices,createMcpExtension,SettingsManager,SessionManager} from '@earendil-works/pi-coding-agent';
import {offlineModelRuntime,planStream,FAKE_MODEL} from ${JSON.stringify(new URL('../harness/pi.mjs',import.meta.url).href)};
import {parseRules} from './dist/policy/rules.js';
assert.equal(parseRules('prefix_rule(pattern=["packed"], decision="forbidden")')[0].decision,'forbidden');
const cwd=process.cwd(),agentDir=process.env.GUARD_AGENT_DIR;
const modelRuntime=await offlineModelRuntime({agentDir});
const runtime=await createAgentSessionRuntime(async input=>{
 const services=await createAgentSessionServices({...input,modelRuntime,settingsManager:SettingsManager.inMemory({cacheWarming:'off',compaction:{enabled:false}}),resourceLoaderOptions:{additionalExtensionPaths:[${JSON.stringify(join(consumer,'package/dist/index.js'))}],extensionFactories:[{name:'mcp',factory:createMcpExtension(),replaceable:true}],noSkills:true,noPromptTemplates:true,noThemes:true,noContextFiles:true}});
 assert.equal(services.resourceLoader.getExtensions().errors.length,0);
 const result=await createAgentSessionFromServices({services,sessionManager:input.sessionManager,model:FAKE_MODEL});
 await result.session.bindExtensions({mode:'print'});
 return {...result,services};
},{cwd,agentDir,sessionManager:SessionManager.inMemory(cwd)});
try {
 const events=[];runtime.session.subscribe(event=>events.push(event));
 await planStream(runtime.session,[[{name:'write',args:{path:'packed.txt',content:'packed-effect'}}],[{name:'mcp__stdio__read_owned',args:{value:'owned'}}]]);
 await runtime.session.prompt('Write the owned local file and read the owned MCP sentinel.');
 assert.equal(await readFile('packed.txt','utf8'),'packed-effect');
 const results=events.filter(event=>event.type==='tool_execution_end');
 assert.equal(results.length,2);assert.ok(results.every(event=>!event.isError),JSON.stringify(results));
 assert.ok(JSON.stringify(results[1].result).includes('unchanged'));
 assert.equal(runtime.services.resourceLoader.getExtensions().extensions.filter(extension=>extension.commands.has('mcp')).length,1);
 console.log(JSON.stringify({factoryLoaded:true,workerEffect:true,officialMcp:true,hostVersion:'0.99.1'}));
} finally {await runtime.dispose();}
`);
  const started=Date.now();
  const executed=await exec(process.execPath,[script],{cwd:f.workspace,env:{...env,GUARD_AGENT_DIR:f.agentDir},timeout:20000,maxBuffer:2000000}).catch(error=>{throw new Error(`Packed probe failed after ${Date.now()-started}ms; code=${error.code}; killed=${error.killed}; signal=${error.signal}; stderr=${error.stderr??''}`,{cause:error});});
  assert.match(executed.stdout,/"factoryLoaded":true/);assert.match(executed.stdout,/"officialMcp":true/);assert.equal(await readFile(join(f.workspace,'packed.txt'),'utf8'),'packed-effect');
  const help=await exec(process.execPath,[join(consumer,'package/dist/cli.js'),'--help'],{cwd:f.workspace,env,timeout:10000});assert.match(help.stdout,/사용법/);
});
test('[cleanup] nonempty owned audit population is scanned and native resources settle before disposal', async t => {
  const population=await readFile(auditPopulationPath,'utf8');
  assert.ok(population.trim().split('\n').length>0);assert.ok(!/SYNTHETIC_GUARD_SECRET_[a-z0-9-]+/i.test(population));
  const f=await fixture(t), executor=new NativeExecutor();await executor.qualify(f.profile,f.workspace);
  await executor.execute({kind:'file',operation:'write',path:join(f.workspace,'cleanup.txt'),content:'done',cwd:f.workspace},f.profile,EMPTY_DELTA);
  await executor.close();await assert.rejects(executor.execute({kind:'shell',command:'printf no',cwd:f.workspace},f.profile,EMPTY_DELTA));
  assert.equal(executor.activeInvocationCount,0);
  assert.equal(await readFile(join(f.workspace,'cleanup.txt'),'utf8'),'done');
});
